on:
  pull_request:
    branches:
    # - master
  push:
    branches:
      - githubaction

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Inject insteadOf configuration for l2 private repo
      run: |
        git config --global url."https://${{ secrets.ROLLUP_ACCESS_TOKEN }}:x-oauth-basic@github.com/goshennetwork".insteadOf "https://github.com/goshennetwork"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: command
      run: bash ./.gha.precheck.sh
